export interface BonbastJsonResponse {
  try1: string;
  month: number;
  emami1: string;
  afn2: string;
  afn1: string;
  rub2: string;
  azadi1_22: string;
  bhd2: string;
  azn1: string;
  bhd1: string;
  azadi1g: string;
  bourse: string;
  try2: string;
  cny1: string;
  cny2: string;
  cad1: string;
  cad2: string;
  jpy1: string;
  thb1: string;
  usd1: string;
  usd2: string;
  thb2: string;
  azn2: string;
  dkk1: string;
  amd2: string;
  day: number;
  minute: string;
  amd1: string;
  bitcoin: string;
  hour: string;
  sar2: string;
  rub1: string;
  azadi1g2: string;
  azadi12: string;
  eur1: string;
  eur2: string;
  emami12: string;
  second: string;
  omr1: string;
  year: number;
  chf2: string;
  chf1: string;
  azadi1_42: string;
  jpy2: string;
  kwd2: string;
  kwd1: string;
  sek1: string;
  gbp2: string;
  gbp1: string;
  sek2: string;
  myr1: string;
  myr2: string;
  omr2: string;
  azadi1: string;
  azadi1_2: string;
  aud2: string;
  azadi1_4: string;
  aud1: string;
  dkk2: string;
  inr2: string;
  inr1: string;
  last_modified: Date;
  aed2: string;
  aed1: string;
  iqd2: string;
  qar1: string;
  qar2: string;
  iqd1: string;
  hkd2: string;
  hkd1: string;
  sar1: string;
  created: Date;
  sgd2: string;
  sgd1: string;
  ounce: string;
  weekday:
    | "Saturday"
    | "Sunday"
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday";
  mithqal: string;
  gol18: string;
  nok1: string;
  nok2: string;
}
